### ISSUE TITLE
Is there a way to get the current state (On/Off) of the yeelight ?

### ISSUE THREAD

**Issue by rp1231** [Leixb/yeelight-cli#4]
Is there a way to get the current state (On/Off) of the yeelight via a command ?

Thanks

**Comment by rp1231** [comment]
Or atleast off?
Because right now if you send the "yeelight-cli get bright" command when the light is off,
It returns the last brightness instead of "off"

**Comment by Leixb** [comment]
You should be able to do it with `yeelight-cli get power` You can find the full list of properties in: https://docs.rs/yeelight/0.3.0/yeelight/enum.Property.html

**Comment by rp1231** [comment]
Thanks that worked

**Comment by rp1231** [comment]
Hi,

Didn't want to open a new topic for this.
Just wanted to ask how to use the ct command.

I've tried using
yeelight-cli "ip address" set ct 4000
yeelight-cli "ip address" set CT 4000

and what range of values can I use to set the color temperature?

Thanks

**Comment by Leixb** [comment]
@rp1231 the first command should work. Is the light on? It does not work when the light is switched off.

You can use `yeelight-cli on --mode=CT` to turn it on in color temperature mode and see if it works.

Remember that passing `--help` will give information on the program usage and can also be used in subcommands. In this case `yeelight-cli set --help` will show you all the properties that can be set.

The range of values is between 1700 and 6500, but it may vary depending on your light model. 

Hope that helps!

**Comment by rp1231** [comment]
@Leixb 
This is the error I got when I used the command with 1700
![cmd_YkLU6LDiIl](https://user-images.githubusercontent.com/47380919/169395315-d3f4c015-1cba-422b-8db4-d30fac9479d0.png)


> @rp1231 the first command should work. Is the light on? It does not work when the light is switched off.
Yes the light was on.
 
> You can use `yeelight-cli on --mode=CT` to turn it on in color temperature mode and see if it works.
 I'll give this a shot

**Comment by Leixb** [comment]
Try other values. This error happens when the value is not supported by the light model.

**Comment by rp1231** [comment]
Yep the values supported for me are between 3000-6500 as I have the non rgb/CT one.
Strangely enough 4000 didn't work for me before....
But it worked after the ```yeelight-cli on --mode=CT``` command.

Which is strange considering that the bulb I'm using supports only CT so it should be in CT mode by default.....
Or maybe I must have made a mistake in typing it......

Anyways thanks a lot.
